### GET

GET http://localhost:8000/api/products


### POST

POST http://localhost:8000/api/products
Content-Type: application/json

{
    "name": "Test",
    "price": 5000
}


### DELETE
DELETE http://localhost:8000/api/products/22
Content-Type: application/json
