### READ products

GET http://localhost:8000/api/products


### CREATE product

POST http://localhost:8000/api/products
Content-Type: application/json

{
    "name": "Test",
    "price": 5000
}


### DELETE products
DELETE http://localhost:8000/api/products/22
Content-Type: application/json


### READ categories

GET http://localhost:8000/api/categories


### CREATE category

POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "Test",
    "price": 5000
}


### DELETE category
DELETE http://localhost:8000/api/categories/22
Content-Type: application/json


### POST sactum/token
POST http://localhost:8000/api/sanctum/token
Content-Type: application/json

{
    "email": "nestor.okeefe@example.net",
    "password": "password1",
    "device_name": "mobile"
}
