### CONST

@authToken = 2|YJo67S8yZMvi2ly6rcOQBEPtxvuH9dZ8ZOaA1FBp

### READ products

GET http://localhost:8000/api/categories
Content-Type: application/json
Authorization: Bearer {{authToken}}


### CREATE product

POST http://localhost:8000/api/products
Content-Type: application/json


{
    "name": "Test",
    "price": 5000
}


### DELETE products
DELETE http://localhost:8000/api/products/22
Content-Type: application/json


### READ categories

GET http://localhost:8000/api/categories


### CREATE category

POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "Test",
    "price": 5000
}


### DELETE category
DELETE http://localhost:8000/api/categories/22
Content-Type: application/json


### POST sactum/token
POST http://localhost:8000/api/sanctum/token
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "abcd1234",
    "device_name": "mobile"
}

### POST newsletter
POST http://localhost:8000/api/newsletter/send
Content-Type: application/json
Authorization: Bearer {{authToken}}

### POST score
POST http://localhost:8000/api/products/2/rate
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "score": 10
}
